import { GEMINI_MODEL } from "../../utils/config";
import { GoogleGenAI } from "@google/genai";
import { readGoogleDoc } from "../DocsApi/readGoogleDocs";
import { z } from "zod";

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;

const genAi = new GoogleGenAI({apiKey: GEMINI_API_KEY});

// export const readGoogleDocsTool = new FunctionTool({
//   name: 'read_google_doc',
//   description: 'Reads the content of a Google Doc given its ID and access token.',
//   parameters: z.object({
//     docId: z.string().describe('The Google Doc ID to read.'),
//     accessToken: z.string().describe('The OAuth access token with Google Docs API permission.'),
//   }),
//   execute: async ({ docId, accessToken }) => {
//     try {
//       const content = await readGoogleDoc(docId, accessToken);
//       return { status: 'success', content };
//     } catch (err) {
//       return { status: 'error', message: (err as Error).message };
//     }
//   },
// });

// export const googleDocsAgent = new LlmAgent({
//   name: 'google_docs_reader_agent',
//   model: 'gemini-3.1-flash-lite-preview',
//   description: 'Agent that can read the content of a Google Doc when given the ID and access token.',
//   instruction: `
//     You are a helpful assistant that reads Google Docs.
//     When a user asks you to fetch a document, use the 'read_google_doc' tool.
//   `,
//   tools: [readGoogleDocsTool],
// });

export async function getGeminiResponse(prompt: string): Promise<string> {
    try{
        const response = await genAi.models.generateContent({
            model: GEMINI_MODEL,
            contents: { parts: [{ text: prompt }] },
        });

        const text = response?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!text) {throw new Error("No response generated by Gemini");}
        return text;

        

    } catch (error) {    
        const errorMsg = error instanceof Error ? error.message : String(error);
        throw new Error(`Gemini API error: ${errorMsg}`);
    }


    // const response = await fetch(
    // `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`,    {
    //     method: "POST",
    //     headers: {
    //         "Content-Type": "application/json",
    //     },
    //     body: JSON.stringify({
    //         contents: [
    //         {
    //             parts: [{ text: prompt }],
    //         },
    //         ],
    //     }),
    //     }
    // );

    // if (!response.ok) {
    //     const errorText = await response.text();
    //     throw new Error(`Gemini API error: ${response.status} ${errorText}`);
    // }

    // const data = await response.json();

    // return (
    //     data?.candidates?.[0]?.content?.parts?.[0]?.text ||
    //     "Sorry, no response generated."
    // );
}