import { GEMINI_MODEL } from "../../utils/config";
import { GoogleGenAI } from "@google/genai";

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;

const genAi = new GoogleGenAI({apiKey: GEMINI_API_KEY});


export async function getGeminiResponse(prompt: string): Promise<string> {
    try{
        const response = await genAi.models.generateContent({
            model: GEMINI_MODEL,
            contents: { parts: [{ text: prompt }] }
        });

        const text = response?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!text) {throw new Error("No response generated by Gemini");}
        return text;

    } catch (error) {    
        const errorMsg = error instanceof Error ? error.message : String(error);
        throw new Error(`Gemini API error: ${errorMsg}`);
    }


    // const response = await fetch(
    // `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`,    {
    //     method: "POST",
    //     headers: {
    //         "Content-Type": "application/json",
    //     },
    //     body: JSON.stringify({
    //         contents: [
    //         {
    //             parts: [{ text: prompt }],
    //         },
    //         ],
    //     }),
    //     }
    // );

    // if (!response.ok) {
    //     const errorText = await response.text();
    //     throw new Error(`Gemini API error: ${response.status} ${errorText}`);
    // }

    // const data = await response.json();

    // return (
    //     data?.candidates?.[0]?.content?.parts?.[0]?.text ||
    //     "Sorry, no response generated."
    // );
}